{% set name = "ocp" %}
{% set version = "7.6.3.0" %}
{% set occt_ver = "7.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # currently only used for the license file
  - url: https://raw.githubusercontent.com/CadQuery/OCP/{{ version }}/LICENSE
    fn: {{ name }}-{{ version }}-LICENSE.txt
    sha256: a13caea71627202ad33cc4cafafdd18e667e16716488f8d9c568127121fb89fd

  # binding sources
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_windows-2019.zip"  # [win]
    sha256: a7273a46540eda2201bfc49ccc744deb8b08f0058ace7a334b81a68764e18293  # [win]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_macOS-10.15.zip"   # [osx]
    sha256: b63f9e36526ecc08f1e96e601118dbeeea8b9da2ddbb3bdcfe3e02f952f1fe34  # [osx]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_Ubuntu-18.04.zip"  # [linux]
    sha256: 5c4679cc01c6b9fa75b45c68424f5611e90a6ad94bec8a2d6e8e3902c1e7e5d3  # [linux]
    folder: src
    patches: CMakeLists-Zm10-win.patch  # [win]

build:
  number: 2

requirements:
  build:
    - python                              # [ build_platform != target_platform ]
    - cross-python_{{ target_platform }}  # [ build_platform != target_platform ]
    - pybind11                            # [ build_platform != target_platform ]
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - lld  # [win]
  host:
    - python
    - pybind11
    - pybind11-abi
    - occt {{ occt_ver }}
    - vtk
  run:
    - python
    - {{ pin_compatible('occt', max_pin='x.x.x') }}
    - vtk

test:
  imports:
    - OCP
    - OCP.WNT    # [win]
    - OCP.Xw     # [linux]
    - OCP.Cocoa  # [osx]

about:
  home: https://github.com/CadQuery/OCP/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}-LICENSE.txt
  summary: 'Python wrapper for OCCT using auto-generated pybind11 bindings.'
  doc_url: https://github.com/CadQuery/OCP/blob/master/README.md
  dev_url: https://github.com/CadQuery/OCP/

extra:
  recipe-maintainers:
    - whophil
    - adam-urbanczyk
