{% set name = "ocp" %}
{% set version = "7.7.2.0" %}
{% set occt_ver = "7.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # currently only used for the license file
  - url: https://raw.githubusercontent.com/CadQuery/OCP/{{ version }}/LICENSE
    fn: {{ name }}-{{ version }}-LICENSE.txt
    sha256: a13caea71627202ad33cc4cafafdd18e667e16716488f8d9c568127121fb89fd

  # binding sources
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_windows-2019.zip"  # [win]
    sha256: d48ddf32ac61f29c9f6fdabcc854ec5369c9e2fb1ceb54a965fbfb2b7810cac9  # [win]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_macOS-latest.zip"   # [osx]
    sha256: bc7d56990eac7eb9de8163dc3f538c554eeaf57c51b69df90fc7b65bfeaa2049  # [osx]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Ubuntu-20.04.zip"  # [linux]
    sha256: 1607c056e5d21b661c528f73d623b8cd911603935ade429eea6c6bf492e042cb  # [linux]
    folder: src
    patches: CMakeLists-Zm10-win.patch  # [win]

build:
  number: 1

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - lld  # [win]
    - boost-cpp 1.82.*
  host:
    - python
    - pybind11
    - pybind11-abi
    - occt {{ occt_ver }}
    - vtk
  run:
    - python
    - {{ pin_compatible('occt', exact=True) }}
    - {{ pin_compatible('vtk', max_pin='x.x') }}

test:
  imports:
    - OCP
    - OCP.WNT    # [win]
    - OCP.Xw     # [linux]
    - OCP.Cocoa  # [osx]

about:
  home: https://github.com/CadQuery/OCP/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}-LICENSE.txt
  summary: 'Python wrapper for OCCT using auto-generated pybind11 bindings.'
  doc_url: https://github.com/CadQuery/OCP/blob/master/README.md
  dev_url: https://github.com/CadQuery/OCP/

extra:
  recipe-maintainers:
    - whophil
    - adam-urbanczyk
