{% set name = "ocp" %}
{% set version = "7.8.1.2" %}
{% set occt_ver = "7.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # currently only used for the license file
  - url: https://raw.githubusercontent.com/CadQuery/OCP/{{ version }}/LICENSE
    fn: {{ name }}-{{ version }}-LICENSE.txt
    sha256: a13caea71627202ad33cc4cafafdd18e667e16716488f8d9c568127121fb89fd

  # binding sources
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_windows-2019.zip"  # [win]
    sha256: d81086e3c14d0521f5c5aa9b728c6d52c5e5f76616939fa60e6c1165a0e22b3e  # [win]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_macOS-latest.zip"  # [osx]
    sha256: 180189966d68bd767bc82516a5f99ca09e5d05facd54a2bc3428ecfbb43fc4d2  # [osx]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Ubuntu-20.04.zip"  # [linux]
    sha256: 56d1428a800ba31fc1ce2ea855e0f69bfe72d1abe3467401fec6cdb1741ec250  # [linux]
    folder: src
    patches: CMakeLists-Zm10-win.patch  # [win]

build:
  number: 0

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - lld  # [win]
  host:
    - python
    - pybind11
    - pybind11-abi
    - libboost-devel
    - libgl-devel  # [linux]
    - xorg-xorgproto  # [linux]
    - occt {{ occt_ver }}
    - occt * all*
    - tbb-devel
    - vtk
  run:
    - python
    - {{ pin_compatible('occt', exact=True) }}
    - {{ pin_compatible('vtk', max_pin='x.x') }}
    - occt * all*

test:
  imports:
    - OCP
    - OCP.WNT    # [win]
    - OCP.Xw     # [linux]
    - OCP.Cocoa  # [osx]

about:
  home: https://github.com/CadQuery/OCP/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}-LICENSE.txt
  summary: 'Python wrapper for OCCT using auto-generated pybind11 bindings.'
  doc_url: https://github.com/CadQuery/OCP/blob/master/README.md
  dev_url: https://github.com/CadQuery/OCP/

extra:
  recipe-maintainers:
    - whophil
    - adam-urbanczyk
