{% set name = "ocp" %}
{% set version = "7.9.3.0" %}
{% set occt_ver = "7.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # currently only used for the license file
  - url: https://raw.githubusercontent.com/CadQuery/OCP/{{ version }}/LICENSE
    fn: {{ name }}-{{ version }}-LICENSE.txt
    sha256: a13caea71627202ad33cc4cafafdd18e667e16716488f8d9c568127121fb89fd

  # binding sources
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Windows.zip"  # [win]
    sha256: 7323c79788e83d98eb24b66494f8eeec7d1a4a96f897877d61361603faff418d  # [win]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_OSX.zip"  # [osx]
    sha256: cd0656ff9821f639df128881eae8b9dc92724dcebad3cac2d2bae728fa1ab7e5  # [osx]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Linux.zip"  # [linux]
    sha256: 8861a56da865c6857c9c508f5c42a7201cf74e385e886920aa822a588d55c8e1  # [linux]
    folder: src

build:
  number: 0

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - lld  # [win]
  host:
    - python
    - pybind11
    - pybind11-abi
    - libgl-devel  # [linux]
    - xorg-xorgproto  # [linux]
    - occt {{ occt_ver }}
    - occt * all*
    - tbb-devel
    - vtk
  run:
    - python
    - {{ pin_compatible('occt', exact=True) }}
    - {{ pin_compatible('vtk', max_pin='x.x') }}
    - occt * all*

test:
  imports:
    - OCP
    - OCP.WNT    # [win]
    - OCP.Xw     # [linux]
    - OCP.Cocoa  # [osx]

about:
  home: https://github.com/CadQuery/OCP/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}-LICENSE.txt
  summary: 'Python wrapper for OCCT using auto-generated pybind11 bindings.'
  doc_url: https://github.com/CadQuery/OCP/blob/master/README.md
  dev_url: https://github.com/CadQuery/OCP/

extra:
  recipe-maintainers:
    - whophil
    - adam-urbanczyk
