{% set name = "ocp" %}
{% set version = "8.0.1.0" %}
{% set occt_ver = "8.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # currently only used for the license file
  - url: https://raw.githubusercontent.com/CadQuery/OCP/{{ version }}/LICENSE
    fn: {{ name }}-{{ version }}-LICENSE.txt
    sha256: a13caea71627202ad33cc4cafafdd18e667e16716488f8d9c568127121fb89fd

  # binding sources
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Windows.zip"  # [win]
    sha256: 4e95455ec20e414e303948d419fdf562ed2127cbfbe0dc348ffce737ea199794  # [win]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_OSX.zip"  # [osx]
    sha256: 2b59073821db67cf93f3cbfea90b715b9322a4f8b39aeea18dd6e65458cf736b  # [osx]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Linux.zip"  # [linux]
    sha256: b0b83c661c1c5ec70371314a13267a0d1515eb72d860dd9c80d79ee7985e4fec  # [linux]
    folder: src

build:
  number: 1

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - lld  # [win]
  host:
    - python
    - pybind11
    - pybind11-abi
    - libgl-devel  # [linux]
    - xorg-xorgproto  # [linux]
    - occt {{ occt_ver }}
    - occt * all*
    - tbb-devel
    - vtk
    - fmt
  run:
    - python
    - {{ pin_compatible('occt', exact=True) }}
    - {{ pin_compatible('vtk', max_pin='x.x') }}
    - occt * all*

test:
  imports:
    - OCP
    - OCP.WNT    # [win]
    - OCP.Xw     # [linux]
    - OCP.Cocoa  # [osx]

about:
  home: https://github.com/CadQuery/OCP/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}-LICENSE.txt
  summary: 'Python wrapper for OCCT using auto-generated pybind11 bindings.'
  doc_url: https://github.com/CadQuery/OCP/blob/master/README.md
  dev_url: https://github.com/CadQuery/OCP/

extra:
  recipe-maintainers:
    - whophil
    - adam-urbanczyk
