{% set name = "ocp" %}
{% set version = "8.0.1.1" %}
{% set occt_ver = "8.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # currently only used for the license file
  - url: https://raw.githubusercontent.com/CadQuery/OCP/{{ version }}/LICENSE
    fn: {{ name }}-{{ version }}-LICENSE.txt
    sha256: a13caea71627202ad33cc4cafafdd18e667e16716488f8d9c568127121fb89fd

  # binding sources
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Windows.zip"  # [win]
    sha256: 8dffbda32e5c99478360867c1278b20f51931a1075ae3145d7c0db8dbf9200db  # [win]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_OSX.zip"  # [osx]
    sha256: 9b811c378ab7360a004af45f7f254226ac724b7189f8eabafcd8ffafcf278f0e  # [osx]
  - url: "https://github.com/CadQuery/OCP/releases/download/{{ version }}/OCP_src_stubs_Linux.zip"  # [linux]
    sha256: bbab4dc85fdba87ac8f024e13a3e9dba0e268f4b204c9c60c53edf2522ced46e  # [linux]
    folder: src

build:
  number: 0

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - lld  # [win]
  host:
    - python
    - pybind11
    - pybind11-abi
    - libgl-devel  # [linux]
    - xorg-xorgproto  # [linux]
    - occt {{ occt_ver }}
    - occt * all*
    - tbb-devel
    - vtk
    - fmt
  run:
    - python
    - {{ pin_compatible('occt', exact=True) }}
    - {{ pin_compatible('vtk', max_pin='x.x') }}
    - occt * all*

test:
  imports:
    - OCP
    - OCP.WNT    # [win]
    - OCP.Xw     # [linux]
    - OCP.Cocoa  # [osx]

about:
  home: https://github.com/CadQuery/OCP/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}-LICENSE.txt
  summary: 'Python wrapper for OCCT using auto-generated pybind11 bindings.'
  doc_url: https://github.com/CadQuery/OCP/blob/master/README.md
  dev_url: https://github.com/CadQuery/OCP/

extra:
  recipe-maintainers:
    - whophil
    - adam-urbanczyk
