azure:
  store_build_artifacts: false
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
